dist: bionic

language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.cache/composer

matrix:
  include:
    - env: RUN_PHPSTAN="yes"
    - env: RUN_PSALM="yes"

branches:
  only:
    - master
    - /^\d.\d+$/

before_script:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Read-only OAuth token to work around GitHub API rate limits
  - composer config -g github-oauth.github.com "4b3b0a83ea27d9544d3608a384c7a14625a98804"

  # Install Flex as a global dependency to enable usage of extra.symfony.require
  # while keeping Flex recipes from applying
  - composer global require --no-scripts symfony/flex

  - composer update --no-suggest --prefer-dist

script:
  - composer validate --strict
  - if [ "$RUN_PHPSTAN" != "" ] ; then composer phpstan ; fi
  - if [ "$RUN_PSALM" != "" ] ; then composer psalm ; fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "gJFCZkD2frS1J0bMEXbFFnRQn/GvVXVIKJ980uOLhLwyNK9XZfA8ySbT8I7+PQ2yGp9z72fBE1sBZaFNo5NilulQMpNUj5Ziofd92KLtGQZMcMxMkBy0AaNuootWVJWhlKLkHamVUHM8QKz4JLW2uUgzo8PShX7RU2AcY8MuWgJKdYG8C3q6BhbSHvCcJxCEy9R/DeMDObZYH50oYx+uRKca5yyS0NFLpXRNsSJ/D//ilr1qxFo8DogNPoCFfGAiBn11Z/SmQZiumhsJCb9mdbEPzxXVWPAnwVGYENA2X0yeFdio6r83MIl00CLbH4gaHWVSjwRtFAG1bHFAk75E1837t66IhQKX1MOVmG+sMgEp5nz1WHMPxSRR3y2v4SqbKLkrn5UkkFbzgKMdU1deJ+bw2nbat7eMt3YDy3aP6huWwEXQYrsgjzNPSp6gxVCSHv0k9MtIFnGYu2ZXvDJDXwCtIey6fgyYGAymIdpneJ3Jnyixvr9YeVrpnQDLheRkO/VT6bj1BWwbvYJJ7Zy0ZBYjKHrhO5hYUgFNl7NC5ioAYlfaJqA9O3/ySewEk469IFAAsoQhtgxHf0FfcpoNph/NYbEMGY8QXzsVm4Zf133FkwxLnyzwU0VkhL21bUoLQTVNjNbHEz0/d05C3cs8/yn7fAsDk/UjXPcVqu09SgU="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
